// Script to fetch English translations from Quran.com API and write to a static data file.
// Translation: Saheeh International (ID 20)
// Only fetches translations for verses that have corresponding audio files.
// Generated file: src/data/verses_translation_en.js
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.join(__dirname, '..');

const TRANSLATION_ID = 20; // Saheeh International

// Parse clip filename to extract range
function parseRange(filename) {
  const nameWithoutExt = filename.replace(/\.mp3$/, '');
  const parts = nameWithoutExt.split('_');
  if (parts.length !== 2) return null;
  return parts[1]; // Returns range like "1-7" or "154-157"
}

// Parse range string to get all verse numbers
function getVerseNumbersFromRange(range) {
  if (!range) return [];
  const parts = range.split('-');
  if (parts.length !== 2) return [];
  const start = parseInt(parts[0], 10);
  const end = parseInt(parts[1], 10);
  if (isNaN(start) || isNaN(end) || start < 1 || end < start) return [];
  const verses = [];
  for (let i = start; i <= end; i++) verses.push(i);
  return verses;
}

// Extract needed verse ranges from the audio files on disk
function extractVerseRanges() {
  const clipsPath = path.join(rootDir, 'public', 'audio_files');
  const surahVersesMap = {};

  if (!fs.existsSync(clipsPath)) {
    console.log('Clips folder not found');
    return surahVersesMap;
  }

  const surahFolders = fs.readdirSync(clipsPath)
    .filter(item => fs.statSync(path.join(clipsPath, item)).isDirectory());

  surahFolders.forEach(folder => {
    const match = folder.match(/^(\d+)-/);
    if (!match) return;

    const surahNumber = parseInt(match[1], 10);
    const folderPath = path.join(clipsPath, folder);
    const files = fs.readdirSync(folderPath).filter(file => file.endsWith('.mp3'));
    if (files.length === 0) return;

    if (!surahVersesMap[surahNumber]) surahVersesMap[surahNumber] = new Set();

    files.forEach(file => {
      const range = parseRange(file);
      if (range) {
        getVerseNumbersFromRange(range).forEach(v => surahVersesMap[surahNumber].add(v));
      }
    });
  });

  const result = {};
  Object.keys(surahVersesMap).forEach(surahNum => {
    result[surahNum] = Array.from(surahVersesMap[surahNum]).sort((a, b) => a - b);
  });
  return result;
}

// Fetch all translations for a chapter from Quran.com API
async function fetchTranslationsForChapter(surahNumber) {
  // per_page=300 covers the longest chapter (Al-Baqarah: 286 verses) in one request
  const url = `https://api.quran.com/api/v4/verses/by_chapter/${surahNumber}?translations=${TRANSLATION_ID}&per_page=300`;

  try {
    const response = await fetch(url);
    if (!response.ok) {
      throw new Error(`HTTP error! status: ${response.status}`);
    }

    const data = await response.json();
    const translationsMap = {};

    if (data.verses && Array.isArray(data.verses)) {
      data.verses.forEach(verse => {
        const verseNumber = verse.verse_number;
        const text = verse.translations?.[0]?.text;
        if (verseNumber && text) {
          // Strip <sup> footnote markers (including their content) then any remaining tags
          translationsMap[verseNumber] = text.replace(/<sup[^>]*>.*?<\/sup>/g, '').replace(/<[^>]*>/g, '').trim();
        }
      });
    }

    return translationsMap;
  } catch (error) {
    console.error(`Error fetching translations for chapter ${surahNumber}:`, error.message);
    return {};
  }
}

// Fetch translations for only the needed verses in a surah
async function fetchTranslationsForSurah(surahNumber, verseNumbers) {
  const allTranslations = await fetchTranslationsForChapter(surahNumber);

  const translations = {};
  for (const verseNum of verseNumbers) {
    if (allTranslations[verseNum]) {
      translations[verseNum] = allTranslations[verseNum];
      console.log(`  ✓ Verse ${verseNum}`);
    } else {
      console.log(`  ✗ Verse ${verseNum} — not found in API response`);
      translations[verseNum] = '';
    }
  }

  // Small delay to avoid rate limiting
  await new Promise(resolve => setTimeout(resolve, 500));

  return translations;
}

// Generate the static JS file content
function generateTranslationFileContent(allTranslations, surahNumbers) {
  const apiEndpoint = `https://api.quran.com/api/v4/verses/by_chapter/{chapter}?translations=${TRANSLATION_ID}&per_page=300`;

  let content = `// English translation of the Quran — Saheeh International (ID ${TRANSLATION_ID})
// Generated based on audio files in public/audio_files/ folder
// Only includes verses that have corresponding audio files
// Generated by scripts/fetchTranslationsFromAPI.js
//
// SOURCE: Quran.com API — Translation ID ${TRANSLATION_ID}
// API: ${apiEndpoint}

export const verses = {
`;

  surahNumbers.forEach(surahNum => {
    const translations = allTranslations[surahNum];
    if (!translations || Object.keys(translations).length === 0) return;

    const verseNumbers = Object.keys(translations).map(Number).sort((a, b) => a - b);
    content += `  ${surahNum}: {\n`;
    content += `    // Verses needed: ${verseNumbers.join(', ')}\n`;
    verseNumbers.forEach(verseNum => {
      const text = translations[verseNum] || '';
      const escapedText = text.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
      content += `    ${verseNum}: "${escapedText}",\n`;
    });
    content += `  },\n`;
  });

  content += `};

export function getVersesForSurah(surahNumber) {
  return verses[surahNumber] || null;
}

export function getVerse(surahNumber, verseNumber) {
  const surahVerses = verses[surahNumber];
  if (!surahVerses || !surahVerses[verseNumber]) return null;
  return surahVerses[verseNumber];
}

export function getAvailableVerseNumbers(surahNumber) {
  const surahVerses = verses[surahNumber];
  if (!surahVerses) return [];
  return Object.keys(surahVerses).map(Number).sort((a, b) => a - b);
}
`;

  return content;
}

// Main
async function fetchTranslations() {
  console.log('Extracting verse ranges from audio files...\n');
  const verseRanges = extractVerseRanges();

  const surahNumbers = Object.keys(verseRanges).map(Number).sort((a, b) => a - b);

  if (surahNumbers.length === 0) {
    console.log('No audio files found. Nothing to fetch.');
    return;
  }

  console.log('Found verses needed:');
  surahNumbers.forEach(surahNum => {
    const verses = verseRanges[surahNum];
    const min = Math.min(...verses);
    const max = Math.max(...verses);
    console.log(`  Surah ${surahNum}: verses ${min}–${max} (${verses.length} verses)`);
  });

  console.log(`\nFetching translations from Quran.com API (ID ${TRANSLATION_ID} — Saheeh International)...\n`);

  const allTranslations = {};

  for (const surahNum of surahNumbers) {
    const verseNumbers = verseRanges[surahNum];
    if (verseNumbers.length === 0) continue;

    console.log(`Fetching translations for Surah ${surahNum}...`);
    allTranslations[surahNum] = await fetchTranslationsForSurah(surahNum, verseNumbers);
    console.log(`Completed Surah ${surahNum}\n`);
  }

  const filePath = path.join(rootDir, 'src', 'data', 'verses_translation_en.js');
  fs.writeFileSync(filePath, generateTranslationFileContent(allTranslations, surahNumbers));
  console.log(`✅ verses_translation_en.js written to: ${filePath}`);
  console.log('\n✅ Translation fetch complete.');
}

fetchTranslations().catch(error => {
  console.error('Error fetching translations:', error);
  process.exit(1);
});
