// Script to fetch Arabic verses from Quran.com API and update verses data files
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.join(__dirname, '..');

// Parse clip filename to extract range
function parseRange(filename) {
  const nameWithoutExt = filename.replace(/\.mp3$/, '');
  const parts = nameWithoutExt.split('_');
  if (parts.length !== 2) {
    return null;
  }
  return parts[1]; // Returns range like "1-7" or "154-157"
}

// Parse range string to get all verse numbers
function getVerseNumbersFromRange(range) {
  if (!range) return [];
  const parts = range.split('-');
  if (parts.length !== 2) return [];

  const start = parseInt(parts[0], 10);
  const end = parseInt(parts[1], 10);

  if (isNaN(start) || isNaN(end) || start < 1 || end < start) return [];

  const verses = [];
  for (let i = start; i <= end; i++) {
    verses.push(i);
  }
  return verses;
}

// Extract verse ranges from clips folder
function extractVerseRanges() {
  const clipsPath = path.join(rootDir, 'public', 'audio_files');
  const surahVersesMap = {}; // { surahNumber: Set of verse numbers }

  if (!fs.existsSync(clipsPath)) {
    console.log('Clips folder not found');
    return surahVersesMap;
  }

  const surahFolders = fs.readdirSync(clipsPath)
    .filter(item => {
      const itemPath = path.join(clipsPath, item);
      return fs.statSync(itemPath).isDirectory();
    });

  surahFolders.forEach(folder => {
    const match = folder.match(/^(\d+)-/);
    if (!match) return;

    const surahNumber = parseInt(match[1], 10);
    const folderPath = path.join(clipsPath, folder);
    const files = fs.readdirSync(folderPath)
      .filter(file => file.endsWith('.mp3'));

    if (files.length === 0) return;

    if (!surahVersesMap[surahNumber]) {
      surahVersesMap[surahNumber] = new Set();
    }

    files.forEach(file => {
      const range = parseRange(file);
      if (range) {
        const verseNumbers = getVerseNumbersFromRange(range);
        verseNumbers.forEach(v => surahVersesMap[surahNumber].add(v));
      }
    });
  });

  // Convert Sets to sorted arrays
  const result = {};
  Object.keys(surahVersesMap).forEach(surahNum => {
    result[surahNum] = Array.from(surahVersesMap[surahNum]).sort((a, b) => a - b);
  });

  return result;
}

// Fetch all verses for a chapter from Quran.com API by script type
async function fetchVersesForChapterByScript(surahNumber, script) {
  const scriptConfig = {
    uthmani: { endpoint: 'uthmani', field: 'text_uthmani' },
    indopak: { endpoint: 'indopak', field: 'text_indopak' },
  };

  const { endpoint, field } = scriptConfig[script];

  try {
    const url = `https://api.quran.com/api/v4/quran/verses/${endpoint}?chapter_number=${surahNumber}`;

    const response = await fetch(url);
    if (!response.ok) {
      throw new Error(`HTTP error! status: ${response.status}`);
    }

    const data = await response.json();

    const versesMap = {};
    if (data.verses && Array.isArray(data.verses)) {
      data.verses.forEach(verse => {
        if (verse.verse_key && verse[field]) {
          const verseNumber = parseInt(verse.verse_key.split(':')[1], 10);
          if (!isNaN(verseNumber) && verseNumber > 0) {
            versesMap[verseNumber] = verse[field];
          }
        }
      });
    }

    return versesMap;
  } catch (error) {
    console.error(`Error fetching ${script} verses for chapter ${surahNumber}:`, error.message);
    return {};
  }
}

// Fetch needed verses for a surah by script type
async function fetchVersesForSurah(surahNumber, verseNumbers, script) {
  const allVerses = await fetchVersesForChapterByScript(surahNumber, script);

  const verses = {};
  for (const verseNum of verseNumbers) {
    if (allVerses[verseNum]) {
      verses[verseNum] = allVerses[verseNum];
      console.log(`  ✓ [${script}] Verse ${verseNum}`);
    } else {
      console.log(`  ✗ [${script}] Verse ${verseNum} - not found in API response`);
      verses[verseNum] = "";
    }
  }

  // Add a small delay to avoid rate limiting
  await new Promise(resolve => setTimeout(resolve, 500));

  return verses;
}

// Generate JS file content for a given script's verse data
function generateVersesFileContent(allVerses, surahNumbers, script) {
  const scriptLabels = {
    uthmani: 'Uthmani (Madani)',
    indopak: 'IndoPak',
  };
  const apiEndpoint = `https://api.quran.com/api/v4/quran/verses/${script}`;

  let content = `// Arabic verses of the Quran — ${scriptLabels[script]} script
// Generated based on audio files in public/audio_files/ folder
// Only includes verses that have corresponding audio files
// Generated by scripts/fetchVersesFromAPI.js
//
// SOURCE: Arabic text fetched from Quran.com API (${scriptLabels[script]} script)
// API: ${apiEndpoint}

export const verses = {
`;

  surahNumbers.forEach(surahNum => {
    const verses = allVerses[surahNum];
    if (!verses || Object.keys(verses).length === 0) return;

    const verseNumbers = Object.keys(verses).map(Number).sort((a, b) => a - b);
    content += `  ${surahNum}: {\n`;
    content += `    // Verses needed: ${verseNumbers.join(', ')}\n`;
    verseNumbers.forEach(verseNum => {
      const text = verses[verseNum] || "";
      const escapedText = text.replace(/"/g, '\\"');
      content += `    ${verseNum}: "${escapedText}",\n`;
    });
    content += `  },\n`;
  });

  content += `};

export function getVersesForSurah(surahNumber) {
  return verses[surahNumber] || null;
}

export function getVerse(surahNumber, verseNumber) {
  const surahVerses = verses[surahNumber];
  if (!surahVerses || !surahVerses[verseNumber]) {
    return null;
  }
  return surahVerses[verseNumber];
}

export function getAvailableVerseNumbers(surahNumber) {
  const surahVerses = verses[surahNumber];
  if (!surahVerses) return [];
  return Object.keys(surahVerses).map(Number).sort((a, b) => a - b);
}
`;

  return content;
}

// Main function
async function rebuildVerses() {
  console.log('Extracting verse ranges from audio files...\n');
  const verseRanges = extractVerseRanges();

  console.log('Found verses needed:');
  Object.keys(verseRanges).forEach(surahNum => {
    const verses = verseRanges[surahNum];
    const min = Math.min(...verses);
    const max = Math.max(...verses);
    console.log(`  Surah ${surahNum}: verses ${min}-${max} (${verses.length} verses)`);
  });

  const surahNumbers = Object.keys(verseRanges).map(Number).sort((a, b) => a - b);
  const scripts = ['uthmani', 'indopak'];

  for (const script of scripts) {
    console.log(`\nFetching ${script} Arabic text from Quran.com API...\n`);

    const allVerses = {};

    for (const surahNum of surahNumbers) {
      const verseNumbers = verseRanges[surahNum];
      if (verseNumbers.length === 0) continue;

      console.log(`Fetching verses for Surah ${surahNum} [${script}]...`);
      allVerses[surahNum] = await fetchVersesForSurah(surahNum, verseNumbers, script);
      console.log(`Completed Surah ${surahNum} [${script}]\n`);
    }

    const filename = `verses_${script}.js`;
    const filePath = path.join(rootDir, 'src', 'data', filename);
    fs.writeFileSync(filePath, generateVersesFileContent(allVerses, surahNumbers, script));
    console.log(`✅ ${filename} written to: ${filePath}`);
  }

  console.log('\n✅ All verse files generated successfully.');
}

// Run the script
rebuildVerses().catch(error => {
  console.error('Error rebuilding verses:', error);
  process.exit(1);
});
