// Script to scan audio folders and generate clip manifest
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.join(__dirname, '..');

// Parse clip filename to extract reciter and range
function parseClipFilename(filename) {
  const nameWithoutExt = filename.replace(/\.mp3$/, '');
  const parts = nameWithoutExt.split('_');
  if (parts.length !== 2) {
    return null;
  }

  const [reciterName, range] = parts;
  const formattedReciter = reciterName
    .replace(/([a-z])([A-Z])/g, '$1 $2')
    .replace(/([A-Z])([A-Z][a-z])/g, '$1 $2');

  return {
    reciter: formattedReciter,
    range: range,
    displayName: `${formattedReciter} (${range})`
  };
}

// Scan clips folder
function scanClipsFolder(surahNumber, surahName) {
  const folderName = `${surahNumber}-${surahName}`;
  const folderPath = path.join(rootDir, 'public', 'audio_files', folderName);
  
  if (!fs.existsSync(folderPath)) {
    return [];
  }
  
  const files = fs.readdirSync(folderPath)
    .filter(file => file.endsWith('.mp3'))
    .map(file => {
      const parsed = parseClipFilename(file);
      if (parsed) {
        return {
          filename: file,
          reciter: parsed.reciter,
          range: parsed.range,
          displayName: parsed.displayName,
          isClip: true
        };
      } else {
        console.warn(`⚠️  Skipping file "${file}" in clips/${folderName}/ - filename must match pattern: ReciterName_Range.mp3 (e.g., ShiekhMagdiOsman_1-6.mp3)`);
        return null;
      }
    })
    .filter(Boolean);
  
  return files;
}

// Generate clip manifest
function generateManifests() {
  const surahNames = [
    'Al-Fatihah', 'Al-Baqarah', 'Al-Imran', 'An-Nisa', 'Al-Ma\'idah', 'Al-An\'am', 'Al-A\'raf', 'Al-Anfal', 'At-Tawbah', 'Yunus',
    'Hud', 'Yusuf', 'Ar-Ra\'d', 'Ibrahim', 'Al-Hijr', 'An-Nahl', 'Al-Isra', 'Al-Kahf', 'Maryam', 'Ta-Ha',
    'Al-Anbiya', 'Al-Hajj', 'Al-Mu\'minun', 'An-Nur', 'Al-Furqan', 'Ash-Shu\'ara', 'An-Naml', 'Al-Qasas', 'Al-\'Ankabut', 'Ar-Rum',
    'Luqman', 'As-Sajdah', 'Al-Ahzab', 'Saba', 'Fatir', 'Ya-Sin', 'As-Saffat', 'Sad', 'Az-Zumar', 'Ghafir',
    'Fussilat', 'Ash-Shura', 'Az-Zukhruf', 'Ad-Dukhan', 'Al-Jathiyah', 'Al-Ahqaf', 'Muhammad', 'Al-Fath', 'Al-Hujurat', 'Qaf',
    'Adh-Dhariyat', 'At-Tur', 'An-Najm', 'Al-Qamar', 'Ar-Rahman', 'Al-Waqi\'ah', 'Al-Hadid', 'Al-Mujadilah', 'Al-Hashr', 'Al-Mumtahanah',
    'As-Saff', 'Al-Jumu\'ah', 'Al-Munafiqun', 'At-Taghabun', 'At-Talaq', 'At-Tahrim', 'Al-Mulk', 'Al-Qalam', 'Al-Haqqah', 'Al-Ma\'arij',
    'Nuh', 'Al-Jinn', 'Al-Muzzammil', 'Al-Muddaththir', 'Al-Qiyamah', 'Al-Insan', 'Al-Mursalat', 'An-Naba', 'An-Nazi\'at', '\'Abasa',
    'At-Takwir', 'Al-Infitar', 'Al-Mutaffifin', 'Al-Inshiqaq', 'Al-Buruj', 'At-Tariq', 'Al-A\'la', 'Al-Ghashiyah', 'Al-Fajr', 'Al-Balad',
    'Ash-Shams', 'Al-Lail', 'Ad-Duhaa', 'Ash-Sharh', 'At-Tin', 'Al-\'Alaq', 'Al-Qadr', 'Al-Bayyina', 'Az-Zalzalah', 'Al-\'Adiyat',
    'Al-Qari\'ah', 'At-Takathur', 'Al-\'Asr', 'Al-Humazah', 'Al-Fil', 'Quraish', 'Al-Ma\'un', 'Al-Kawthar', 'Al-Kafirun', 'An-Nasr',
    'Al-Masad', 'Al-Ikhlas', 'Al-Falaq', 'An-Nas'
  ];

  const clipsManifest = {};

  surahNames.forEach((surahName, index) => {
    const surahNumber = index + 1;
    const clipFiles = scanClipsFolder(surahNumber, surahName);

    if (clipFiles.length > 0) {
      clipsManifest[surahNumber] = clipFiles.map(f => ({ filename: f.filename }));
    }
  });

  // Write audio manifest with numeric keys
  const audioManifestPath = path.join(rootDir, 'src', 'data', 'audioManifest.js');
  let audioManifestContent = `// Auto-generated manifest of available clips
// Generated by scripts/generateAudioManifest.js
// Do not edit manually - run 'npm run generate-manifest' to update

import { parseClipFilename } from '../utils/clipParser';

export const audioManifest = {
`;

  Object.keys(clipsManifest).sort((a, b) => parseInt(a) - parseInt(b)).forEach(key => {
    const files = clipsManifest[key];
    audioManifestContent += `  ${key}: ${JSON.stringify(files, null, 4).split('\n').join('\n  ')},\n`;
  });

  audioManifestContent += `};

/**
 * Get clips for a specific surah
 */
export function getClipsForSurah(surahNumber, surahFolderName) {
  const baseUrl = import.meta.env.BASE_URL;
  const clips = audioManifest[surahNumber] || [];

  return clips.map(clip => {
    const parsed = parseClipFilename(clip.filename);
    if (!parsed) return null;

    return {
      name: parsed.displayName,
      reciter: parsed.reciter,
      range: parsed.range,
      url: \`\${baseUrl}audio_files/\${surahFolderName}/\${clip.filename}\`,
      isClip: true
    };
  }).filter(Boolean);
}
`;
  fs.writeFileSync(audioManifestPath, audioManifestContent);

  console.log('Audio manifest generated successfully!');
  console.log(`Found ${Object.keys(clipsManifest).length} surahs with clips`);
}

generateManifests();

