// Script to generate verses data based on audio files in clips folder
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.join(__dirname, '..');

// Parse clip filename to extract range
function parseRange(filename) {
  const nameWithoutExt = filename.replace(/\.mp3$/, '');
  const parts = nameWithoutExt.split('_');
  if (parts.length !== 2) {
    return null;
  }
  return parts[1]; // Returns range like "1-7" or "154-157"
}

// Parse range string to get all verse numbers
function getVerseNumbersFromRange(range) {
  if (!range) return [];
  const parts = range.split('-');
  if (parts.length !== 2) return [];
  
  const start = parseInt(parts[0], 10);
  const end = parseInt(parts[1], 10);
  
  if (isNaN(start) || isNaN(end) || start < 1 || end < start) return [];
  
  const verses = [];
  for (let i = start; i <= end; i++) {
    verses.push(i);
  }
  return verses;
}

// Scan clips folder and extract all verse ranges
function extractVerseRanges() {
  const clipsPath = path.join(rootDir, 'public', 'audio_files', 'clips');
  const surahVersesMap = {}; // { surahNumber: Set of verse numbers }
  
  if (!fs.existsSync(clipsPath)) {
    console.log('Clips folder not found');
    return surahVersesMap;
  }
  
  const surahFolders = fs.readdirSync(clipsPath)
    .filter(item => {
      const itemPath = path.join(clipsPath, item);
      return fs.statSync(itemPath).isDirectory();
    });
  
  surahFolders.forEach(folder => {
    // Extract surah number from folder name (e.g., "1-Al-Fatihah" -> 1)
    const match = folder.match(/^(\d+)-/);
    if (!match) return;
    
    const surahNumber = parseInt(match[1], 10);
    const folderPath = path.join(clipsPath, folder);
    const files = fs.readdirSync(folderPath)
      .filter(file => file.endsWith('.mp3'));
    
    // Only process folders that have files
    if (files.length === 0) return;
    
    if (!surahVersesMap[surahNumber]) {
      surahVersesMap[surahNumber] = new Set();
    }
    
    files.forEach(file => {
      const range = parseRange(file);
      if (range) {
        const verseNumbers = getVerseNumbersFromRange(range);
        verseNumbers.forEach(v => surahVersesMap[surahNumber].add(v));
      }
    });
  });
  
  // Convert Sets to sorted arrays
  const result = {};
  Object.keys(surahVersesMap).forEach(surahNum => {
    result[surahNum] = Array.from(surahVersesMap[surahNum]).sort((a, b) => a - b);
  });
  
  return result;
}

// Generate verses data structure
function generateVersesData() {
  const verseRanges = extractVerseRanges();
  
  console.log('Extracted verse ranges from audio files:');
  Object.keys(verseRanges).forEach(surahNum => {
    const verses = verseRanges[surahNum];
    const min = Math.min(...verses);
    const max = Math.max(...verses);
    console.log(`  Surah ${surahNum}: verses ${min}-${max} (${verses.length} verses needed)`);
  });
  
  // Generate the verses.js file structure
  let versesContent = `// Arabic verses of the Quran
// Generated based on audio files in public/audio_files/clips folder
// Only includes verses that have corresponding audio files
// Generated by scripts/generateVersesData.js
// Do not edit manually - run 'npm run generate-verses' to update

export const verses = {
`;

  // Sort surah numbers
  const surahNumbers = Object.keys(verseRanges).map(Number).sort((a, b) => a - b);
  
  surahNumbers.forEach(surahNum => {
    const verseNumbers = verseRanges[surahNum];
    if (verseNumbers.length === 0) return; // Skip surahs with no verses
    
    versesContent += `  ${surahNum}: {\n`;
    versesContent += `    // Verses needed: ${verseNumbers.join(', ')}\n`;
    versesContent += `    // TODO: Add Arabic text for these verses\n`;
    verseNumbers.forEach(verseNum => {
      versesContent += `    ${verseNum}: "", // Verse ${verseNum} - Arabic text needed\n`;
    });
    versesContent += `  },\n`;
  });
  
  versesContent += `};

/**
 * Get verses for a specific surah
 * @param {number} surahNumber - The surah number (1-114)
 * @returns {Object|null} - Object with verse numbers as keys and Arabic text as values, or null if not found
 */
export function getVersesForSurah(surahNumber) {
  return verses[surahNumber] || null;
}

/**
 * Get a specific verse
 * @param {number} surahNumber - The surah number (1-114)
 * @param {number} verseNumber - The verse number (1-based)
 * @returns {string|null} - The Arabic verse text, or null if not found
 */
export function getVerse(surahNumber, verseNumber) {
  const surahVerses = verses[surahNumber];
  if (!surahVerses || !surahVerses[verseNumber]) {
    return null;
  }
  return surahVerses[verseNumber];
}

/**
 * Get all verse numbers available for a surah
 * @param {number} surahNumber - The surah number (1-114)
 * @returns {number[]} - Array of verse numbers that have Arabic text
 */
export function getAvailableVerseNumbers(surahNumber) {
  const surahVerses = verses[surahNumber];
  if (!surahVerses) return [];
  return Object.keys(surahVerses).map(Number).sort((a, b) => a - b);
}
`;

  const versesPath = path.join(rootDir, 'src', 'data', 'verses.js');
  fs.writeFileSync(versesPath, versesContent);
  
  console.log(`\nVerses data structure generated at: ${versesPath}`);
  console.log('Note: Arabic text needs to be added manually for each verse.');
}

generateVersesData();

