// Script to scan audio folders and generate manifests
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.join(__dirname, '..');

// Parse clip filename to extract reciter and range
function parseClipFilename(filename) {
  const nameWithoutExt = filename.replace(/\.mp3$/, '');
  const parts = nameWithoutExt.split('_');
  if (parts.length !== 2) {
    return null;
  }
  
  const [reciterName, range] = parts;
  const formattedReciter = reciterName
    .replace(/([a-z])([A-Z])/g, '$1 $2')
    .replace(/([A-Z])([A-Z][a-z])/g, '$1 $2');
  
  return {
    reciter: formattedReciter,
    range: range,
    displayName: `${formattedReciter} (${range})`
  };
}

// Scan surah folder
function scanSurahFolder(surahNumber, surahName) {
  const folderName = `${surahNumber}-${surahName}`;
  const folderPath = path.join(rootDir, 'public', 'audio_files', 'surah', folderName);
  
  if (!fs.existsSync(folderPath)) {
    return [];
  }
  
  const files = fs.readdirSync(folderPath)
    .filter(file => file.endsWith('.mp3'))
    .map(file => {
      // Check if it's a clip format (ReciterName_1-10.mp3)
      const parsed = parseClipFilename(file);
      if (parsed) {
        return {
          filename: file,
          reciter: parsed.reciter,
          range: parsed.range,
          displayName: parsed.displayName,
          isClip: false // It's in surah folder but has clip format
        };
      } else {
        // Regular audio file
        return {
          filename: file,
          name: file.replace('.mp3', ''),
          isClip: false
        };
      }
    });
  
  return files;
}

// Scan clips folder
function scanClipsFolder(surahNumber, surahName) {
  const folderName = `${surahNumber}-${surahName}`;
  const folderPath = path.join(rootDir, 'public', 'audio_files', 'clips', folderName);
  
  if (!fs.existsSync(folderPath)) {
    return [];
  }
  
  const files = fs.readdirSync(folderPath)
    .filter(file => file.endsWith('.mp3'))
    .map(file => {
      const parsed = parseClipFilename(file);
      if (parsed) {
        return {
          filename: file,
          reciter: parsed.reciter,
          range: parsed.range,
          displayName: parsed.displayName,
          isClip: true
        };
      }
      return null;
    })
    .filter(Boolean);
  
  return files;
}

// Generate manifests
function generateManifests() {
  const surahNames = [
    'Al-Fatihah', 'Al-Baqarah', 'Al-Imran', 'An-Nisa', 'Al-Ma\'idah', 'Al-An\'am', 'Al-A\'raf', 'Al-Anfal', 'At-Tawbah', 'Yunus',
    'Hud', 'Yusuf', 'Ar-Ra\'d', 'Ibrahim', 'Al-Hijr', 'An-Nahl', 'Al-Isra', 'Al-Kahf', 'Maryam', 'Ta-Ha',
    'Al-Anbiya', 'Al-Hajj', 'Al-Mu\'minun', 'An-Nur', 'Al-Furqan', 'Ash-Shu\'ara', 'An-Naml', 'Al-Qasas', 'Al-\'Ankabut', 'Ar-Rum',
    'Luqman', 'As-Sajdah', 'Al-Ahzab', 'Saba', 'Fatir', 'Ya-Sin', 'As-Saffat', 'Sad', 'Az-Zumar', 'Ghafir',
    'Fussilat', 'Ash-Shura', 'Az-Zukhruf', 'Ad-Dukhan', 'Al-Jathiyah', 'Al-Ahqaf', 'Muhammad', 'Al-Fath', 'Al-Hujurat', 'Qaf',
    'Adh-Dhariyat', 'At-Tur', 'An-Najm', 'Al-Qamar', 'Ar-Rahman', 'Al-Waqi\'ah', 'Al-Hadid', 'Al-Mujadilah', 'Al-Hashr', 'Al-Mumtahanah',
    'As-Saff', 'Al-Jumu\'ah', 'Al-Munafiqun', 'At-Taghabun', 'At-Talaq', 'At-Tahrim', 'Al-Mulk', 'Al-Qalam', 'Al-Haqqah', 'Al-Ma\'arij',
    'Nuh', 'Al-Jinn', 'Al-Muzzammil', 'Al-Muddaththir', 'Al-Qiyamah', 'Al-Insan', 'Al-Mursalat', 'An-Naba', 'An-Nazi\'at', '\'Abasa',
    'At-Takwir', 'Al-Infitar', 'Al-Mutaffifin', 'Al-Inshiqaq', 'Al-Buruj', 'At-Tariq', 'Al-A\'la', 'Al-Ghashiyah', 'Al-Fajr', 'Al-Balad',
    'Ash-Shams', 'Al-Lail', 'Ad-Duhaa', 'Ash-Sharh', 'At-Tin', 'Al-\'Alaq', 'Al-Qadr', 'Al-Bayyina', 'Az-Zalzalah', 'Al-\'Adiyat',
    'Al-Qari\'ah', 'At-Takathur', 'Al-\'Asr', 'Al-Humazah', 'Al-Fil', 'Quraish', 'Al-Ma\'un', 'Al-Kawthar', 'Al-Kafirun', 'An-Nasr',
    'Al-Masad', 'Al-Ikhlas', 'Al-Falaq', 'An-Nas'
  ];
  
  const surahManifest = {};
  const clipsManifest = {};
  
  surahNames.forEach((surahName, index) => {
    const surahNumber = index + 1;
    const surahFiles = scanSurahFolder(surahNumber, surahName);
    const clipFiles = scanClipsFolder(surahNumber, surahName);
    
    if (surahFiles.length > 0) {
      surahManifest[surahNumber] = surahFiles;
    }
    
    if (clipFiles.length > 0) {
      clipsManifest[surahNumber] = clipFiles.map(f => ({ filename: f.filename }));
    }
  });
  
  // Write surah manifest with numeric keys
  const surahManifestPath = path.join(rootDir, 'src', 'data', 'surahManifest.js');
  let surahManifestContent = `// Auto-generated manifest of available surah audio files
// Generated by scripts/generateAudioManifest.js
// Do not edit manually - run 'npm run generate-manifest' to update

export const surahManifest = {
`;
  
  Object.keys(surahManifest).sort((a, b) => parseInt(a) - parseInt(b)).forEach(key => {
    const files = surahManifest[key];
    surahManifestContent += `  ${key}: ${JSON.stringify(files, null, 4).split('\n').join('\n  ')},\n`;
  });
  
  surahManifestContent += `};
`;
  fs.writeFileSync(surahManifestPath, surahManifestContent);
  
  // Write clips manifest with numeric keys
  const clipsManifestPath = path.join(rootDir, 'src', 'data', 'clipsManifest.js');
  let clipsManifestContent = `// Auto-generated manifest of available clips
// Generated by scripts/generateAudioManifest.js
// Do not edit manually - run 'npm run generate-manifest' to update

import { parseClipFilename } from '../utils/clipParser';

export const clipsManifest = {
`;
  
  Object.keys(clipsManifest).sort((a, b) => parseInt(a) - parseInt(b)).forEach(key => {
    const files = clipsManifest[key];
    clipsManifestContent += `  ${key}: ${JSON.stringify(files, null, 4).split('\n').join('\n  ')},\n`;
  });
  
  clipsManifestContent += `};

/**
 * Get clips for a specific surah
 */
export function getClipsForSurah(surahNumber, surahFolderName) {
  const baseUrl = import.meta.env.BASE_URL;
  const clips = clipsManifest[surahNumber] || [];
  
  return clips.map(clip => {
    const parsed = parseClipFilename(clip.filename);
    if (!parsed) return null;
    
    return {
      name: parsed.displayName,
      reciter: parsed.reciter,
      range: parsed.range,
      url: \`\${baseUrl}audio_files/clips/\${surahFolderName}/\${clip.filename}\`,
      isClip: true
    };
  }).filter(Boolean);
}
`;
  fs.writeFileSync(clipsManifestPath, clipsManifestContent);
  
  console.log('Manifests generated successfully!');
  console.log(`Found ${Object.keys(surahManifest).length} surahs with audio`);
  console.log(`Found ${Object.keys(clipsManifest).length} surahs with clips`);
}

generateManifests();

